//////////////////////////////////////////////////////////////////////////
// The Global Reference Atmospheric Model (GRAM) Framework
//
// No recipient of this code should forward copies outside of the United 
// States without explicit approval by NASA Marshall Space Flight Center.
// 
// Module: GRAM common
//////////////////////////////////////////////////////////////////////////

#pragma once

#include <vector>
#include "gram.h"
#include "PerturbedAtmosphere.h"

namespace GRAM {

class ProfileData {
public:
  ProfileData(const Position& p, const AtmosphereState& s, const EphemerisState& e)
  {
    position = p; atmos = s; ephem = e;
  }
  ProfileData(const ProfileData& orig) = default;
  Position position;
  AtmosphereState atmos;
  EphemerisState ephem;
};

//! \brief An abstract base class for collecting GRAM inputs and outputs
//!
//! This defines an interface class for collections of GRAM inputs and outputs.  A Profile
//! subclass is used to generate and store a one-dimensional vector of GRAM data.  Subclasses
//! must implement a generate() function which will generate inputs, call the atmosphere, and
//! store the results.
//! \par Usage
//!    A typical subclass of Profile will be used by first creating and initializing an atmosphere
//!    for the desired planet.  Next, provide that atmosphere to the Profile subclass with 
//!    setAtmosphere().  Then call the generate() function which will generate inputs, 
//!    call the atmosphere model, and store the results.  Finally, access the results with
//!    the getProfile() function.  Results can be provide to a ProfilePrinter for output.
//! \ingroup CommonGRAM
class Profile
{
public:
  Profile();
  Profile(const Profile& orig);
  virtual ~Profile();

  void setAtmosphere(PerturbedAtmosphere& atmos) { atmosphere = &atmos; }
  PerturbedAtmosphere& getAtmosphere() { return *atmosphere; }

  virtual void setInputParameters(const InputParameters& params) {}
  virtual void setInitialPosition(const Position& p) { initialPosition = p; }

  virtual void generate() = 0;

  std::vector<ProfileData>& getProfile() { return profile; }
  const Position& getInitialPosition() { return initialPosition; }

protected:
  PerturbedAtmosphere* atmosphere = nullptr;  //!< The atmosphere model used to generate data.
  std::vector<ProfileData> profile;           //!< The data generated by the profile.
  Position initialPosition;                   //!< The starting position of the trajectory.

};

} // namespace
