# Compatibility wrapper: legacy path forwards to canonical engine split files.
include(joinpath(@__DIR__, "..", "engine", "config", "parallel_config.jl"))
include(joinpath(@__DIR__, "..", "engine", "config", "solver_config.jl"))
include(joinpath(@__DIR__, "..", "engine", "config", "runtime_policy_config.jl"))
include(joinpath(@__DIR__, "..", "engine", "config", "artifact_config.jl"))
include(joinpath(@__DIR__, "..", "engine", "config", "simulation_engine_config.jl"))
include(joinpath(@__DIR__, "..", "engine", "adapters", "from_env.jl"))
include(joinpath(@__DIR__, "..", "engine", "setup.jl"))
include(joinpath(@__DIR__, "..", "engine", "solver_policy.jl"))
include(joinpath(@__DIR__, "..", "engine", "dynamics_rhs.jl"))
include(joinpath(@__DIR__, "..", "engine", "persistence.jl"))
include(joinpath(@__DIR__, "..", "engine", "resume_checkpoint.jl"))
include(joinpath(@__DIR__, "..", "engine", "reporting.jl"))
include(joinpath(@__DIR__, "..", "engine", "execution.jl"))
