steps = 18923
orientation_sim = false
created_utc = "2026-09-07T19:20:34.248"
mission_time_s = 189213.5681351643
schema_version = "1"
spacecraft_count = 11

[files.feather]
size_bytes = 42431394
sha256 = "5db362821bbf7394bdb8cb1293be01bd50040b7444bee280bc799046c98ebbc8"
path = "/home/space-falcon-3/Desktop/ORACLE_SpaceAGORA_Integration/good_responses/comparasion_output/gve_ecc/spaceagora_raw/single_case_mode/h1050km_t1000km/ih0.0deg_it0.0deg/N10/T189214s/gve_ecc_e0.0000_nu0.0000/simulation_results.feather"
