Base.include(@__MODULE__, joinpath(@__DIR__, "..", "helpers", "load_hypr.jl"))
using Test

@testset "Unit Test Placeholder" begin
    @test true
end

include(joinpath(@__DIR__, "example_imports_tests.jl"))
include(joinpath(@__DIR__, "xval_fullarc_provenance_tests.jl"))
include(joinpath(@__DIR__, "environment", "pck_override_order_tests.jl"))
include("gnc/rpo_planner_contract_tests.jl")
include("gnc/direct_rpo_planner_tests.jl")
include("gnc/rpo_planner_adapter_tests.jl")
include("gnc/rpo_planner_compatibility_tests.jl")
include("gnc/rpo_planner_lifecycle_tests.jl")
include("rpo_port_tests.jl")
include("gnc/rpo_ownership_reproducibility_tests.jl")
include("gnc/rpo_configurable_station_tests.jl")
include("gnc/rpo_hypr_manuscript_tests.jl")
include("gnc/planning_boundary_gate_tests.jl")
include("gnc/shared_sampling_tests.jl")
include("gnc/shared_metrics_tests.jl")
include("gnc/rrt_boundary_tests.jl")
include("gnc/shared_retiming_tests.jl")
include(joinpath(@__DIR__, "parallel", "machine_topology_tests.jl"))
include(joinpath(@__DIR__, "parallel", "native_lock_stats_tests.jl"))
include(joinpath(@__DIR__, "parallel", "contention_inputs_tests.jl"))
include(joinpath(@__DIR__, "parallel", "usl_tests.jl"))
include(joinpath(@__DIR__, "parallel", "streaming_trial_tests.jl"))
include(joinpath(@__DIR__, "parallel", "lock_width_cap_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_work_counts_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_robust_timing_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_machine_calibration_tests.jl"))
include(joinpath(@__DIR__, "parallel", "outer_route_persistence_tests.jl"))
include(joinpath(@__DIR__, "parallel", "policy_v2_tests.jl"))
include(joinpath(@__DIR__, "parallel", "predictive_planner_tests.jl"))
include(joinpath(@__DIR__, "parallel", "predictive_campaign_tests.jl"))
include(joinpath(@__DIR__, "parallel", "parallel_flag_tests.jl"))
include(joinpath(@__DIR__, "parallel", "parallel_flag_concurrency_tests.jl"))
include(joinpath(@__DIR__, "parallel", "machine_constants_concurrency_tests.jl"))
include(joinpath(@__DIR__, "parallel", "parallel_flag_process_route_tests.jl"))
include(joinpath(@__DIR__, "parallel", "precompile_state_tests.jl"))
include(joinpath(@__DIR__, "parallel", "process_pool_dispatch_cost_tests.jl"))
include(joinpath(@__DIR__, "parallel", "gram_memory_model_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "third_body_cost_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "harmonics_kernel_identity_tests.jl"))
include(joinpath(@__DIR__, "environment", "gram_isolated_pool_tests.jl"))
include(joinpath(@__DIR__, "environment", "gram_native_collect_tests.jl"))
include(joinpath(@__DIR__, "environment", "gram_wind_determinism_tests.jl"))
include(joinpath(@__DIR__, "environment", "environment_wind_flag_tests.jl"))
include(joinpath(@__DIR__, "simulation", "solution_storage_tests.jl"))
include(joinpath(@__DIR__, "simulation", "rhs_heuristic_defaults_tests.jl"))
include(joinpath(@__DIR__, "parallel", "inner_speedup_curve_tests.jl"))
include(joinpath(@__DIR__, "parallel", "inner_speedup_curve_outer_tests.jl"))
include(joinpath(@__DIR__, "parallel", "predictive_corrections_tests.jl"))
include(joinpath(@__DIR__, "parallel", "predictive_campaign_bookkeeping_tests.jl"))
include(joinpath(@__DIR__, "parallel", "predictive_forced_plan_tests.jl"))
include(joinpath(@__DIR__, "parallel", "ppb_serial_baseline_tests.jl"))
include(joinpath(@__DIR__, "parallel", "ppb_exploration_selection_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "aero_batch_parity_tests.jl"))
include(joinpath(@__DIR__, "parallel", "pool_worker_heap_hint_tests.jl"))
include(joinpath(@__DIR__, "parallel", "benchmark_budget_condition_tests.jl"))
include(joinpath(@__DIR__, "simulation", "third_body_route_parity_tests.jl"))
include(joinpath(@__DIR__, "parallel", "outer_split_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "outer_split_budget_cap_tests.jl"))
include(joinpath(@__DIR__, "parallel", "mixed_dispatch_tests.jl"))
include(joinpath(@__DIR__, "parallel", "density_service_recipe_tests.jl"))
include(joinpath(@__DIR__, "parallel", "process_worker_load_path_tests.jl"))
include(joinpath(@__DIR__, "parallel", "process_worker_preload_tests.jl"))
include(joinpath(@__DIR__, "parallel", "nested_inner_threading_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_batch_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "mc_route_tie_tests.jl"))
include(joinpath(@__DIR__, "parallel", "steady_credit_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_reverify_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "resident_worker_cap_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_reverify_unconfirmed_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_store_path_tests.jl"))
include(joinpath(@__DIR__, "parallel", "one_thread_and_multibody_tests.jl"))
include(joinpath(@__DIR__, "parallel", "nested_effector_guard_tests.jl"))
include(joinpath(@__DIR__, "parallel", "density_callback_light_work_tests.jl"))
include(joinpath(@__DIR__, "parallel", "thermal_callback_light_work_tests.jl"))
include(joinpath(@__DIR__, "simulation", "jac_prototype_tests.jl"))
include(joinpath(@__DIR__, "simulation", "metadata_only_return_tests.jl"))
include(joinpath(@__DIR__, "simulation", "trajectory_recorder_tests.jl"))
include(joinpath(@__DIR__, "simulation", "density_epoch_tests.jl"))
include(joinpath(@__DIR__, "simulation", "harmonics_batch_parity_tests.jl"))
include(joinpath(@__DIR__, "simulation", "rhs_direct_assembly_tests.jl"))
include(joinpath(@__DIR__, "simulation", "touchdown_tests.jl"))
include(joinpath(@__DIR__, "simulation", "vector_event_direction_tests.jl"))
include(joinpath(@__DIR__, "simulation", "linear_tolerance_tests.jl"))
include(joinpath(@__DIR__, "simulation", "split_imex_accuracy_tests.jl"))
include(joinpath(@__DIR__, "gnc", "apollo_descent_tests.jl"))
include(joinpath(@__DIR__, "gnc", "apollo11_landing_tests.jl"))
include(joinpath(@__DIR__, "gnc", "edg_wind_relative_velocity_tests.jl"))
include(joinpath(@__DIR__, "io", "results_assembly_tests.jl"))
include(joinpath(@__DIR__, "quality", "coverage_gate_precompile_exclusion_tests.jl"))
include(joinpath(@__DIR__, "robotics", "runtests.jl"))
include(joinpath(@__DIR__, "environment", "sun_direction_tests.jl"))
include(joinpath(@__DIR__, "environment", "epoch_conversion_tests.jl"))
include(joinpath(@__DIR__, "environment", "terrain_models_tests.jl"))
include(joinpath(@__DIR__, "environment", "gravity_gradient_torque_tests.jl"))
include(joinpath(@__DIR__, "visualization", "arm_tests.jl"))
include(joinpath(@__DIR__, "visualization", "articulation_tests.jl"))
include(joinpath(@__DIR__, "visualization", "atmosphere_tests.jl"))
include(joinpath(@__DIR__, "visualization", "ensemble_tests.jl"))
include(joinpath(@__DIR__, "visualization", "scene_visualization_tests.jl"))
include(joinpath(@__DIR__, "visualization", "viewer_bundle_tests.jl"))
include(joinpath(@__DIR__, "visualization", "terrain_export_tests.jl"))

include(joinpath(@__DIR__, "dynamics", "reaction_wheel_momentum_tests.jl"))
include(joinpath(@__DIR__, "visualization", "demo_options_tests.jl"))
include(joinpath(@__DIR__, "environment", "plume_surface_interaction_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "mesh_aero_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "mesh_aero_threading_tests.jl"))

include("visualization/mission_demo_tests.jl")
include(joinpath(@__DIR__, "mission", "cygnss_ics_tests.jl"))
include(joinpath(@__DIR__, "mission", "cygnss_tracks_tests.jl"))
include(joinpath(@__DIR__, "mission", "cygnss_slew_tests.jl"))

include(joinpath(@__DIR__, "mission", "cygnss_command_replay_tests.jl"))

include(joinpath(@__DIR__, "simulation", "atmospheric_phase_tests.jl"))

include(joinpath(@__DIR__, "simulation", "gram_density_perturbation_tests.jl"))
include(joinpath(@__DIR__, "simulation", "gram_density_perturbation_callback_tests.jl"))
include(joinpath(@__DIR__, "dynamics", "facet_srp_and_thermal_models_tests.jl"))
