using Test

@testset "Unit Test Placeholder" begin
    @test true
end

include(joinpath(@__DIR__, "example_imports_tests.jl"))
include("rpo_port_tests.jl")
include(joinpath(@__DIR__, "parallel", "machine_topology_tests.jl"))
include(joinpath(@__DIR__, "parallel", "native_lock_stats_tests.jl"))
include(joinpath(@__DIR__, "parallel", "contention_inputs_tests.jl"))
include(joinpath(@__DIR__, "parallel", "usl_tests.jl"))
include(joinpath(@__DIR__, "parallel", "streaming_trial_tests.jl"))
include(joinpath(@__DIR__, "parallel", "lock_width_cap_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_work_counts_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_robust_timing_tests.jl"))
include(joinpath(@__DIR__, "parallel", "cost_machine_calibration_tests.jl"))
include(joinpath(@__DIR__, "parallel", "outer_route_persistence_tests.jl"))
include(joinpath(@__DIR__, "parallel", "policy_v2_tests.jl"))
include(joinpath(@__DIR__, "parallel", "outer_split_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "mixed_dispatch_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_batch_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "mc_route_tie_tests.jl"))
include(joinpath(@__DIR__, "parallel", "steady_credit_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_reverify_budget_tests.jl"))
include(joinpath(@__DIR__, "parallel", "resident_worker_cap_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_reverify_unconfirmed_tests.jl"))
include(joinpath(@__DIR__, "parallel", "rhs_store_path_tests.jl"))
include(joinpath(@__DIR__, "parallel", "one_thread_and_multibody_tests.jl"))
include(joinpath(@__DIR__, "simulation", "jac_prototype_tests.jl"))
include(joinpath(@__DIR__, "simulation", "metadata_only_return_tests.jl"))
include(joinpath(@__DIR__, "simulation", "trajectory_recorder_tests.jl"))
include(joinpath(@__DIR__, "simulation", "harmonics_batch_parity_tests.jl"))
include(joinpath(@__DIR__, "simulation", "rhs_direct_assembly_tests.jl"))
include(joinpath(@__DIR__, "io", "results_assembly_tests.jl"))
include(joinpath(@__DIR__, "robotics", "runtests.jl"))
include(joinpath(@__DIR__, "environment", "sun_direction_tests.jl"))
include(joinpath(@__DIR__, "visualization", "arm_tests.jl"))
include(joinpath(@__DIR__, "visualization", "articulation_tests.jl"))
include(joinpath(@__DIR__, "visualization", "atmosphere_tests.jl"))
include(joinpath(@__DIR__, "visualization", "ensemble_tests.jl"))
include(joinpath(@__DIR__, "visualization", "scene_visualization_tests.jl"))
include(joinpath(@__DIR__, "visualization", "viewer_bundle_tests.jl"))

include(joinpath(@__DIR__, "dynamics", "reaction_wheel_momentum_tests.jl"))
