steps = 18923
orientation_sim = false
created_utc = "2026-09-07T19:28:58.194"
mission_time_s = 189213.5681351643
schema_version = "1"
spacecraft_count = 11

[files.feather]
size_bytes = 42431394
sha256 = "374ea4b83cbbbf69d29fdbf55e1d9c4961334a380d6edf23e4438b00b0e3646d"
path = "/home/space-falcon-3/Desktop/ORACLE_SpaceAGORA_Integration/good_responses/comparasion_output/gve_inc_it1.0deg/spaceagora_raw/single_case_mode/h1050km_t1000km/ih0.0deg_it1.0deg/N10/T189214s/gve_inc_e0.0000_nu0.0000/simulation_results.feather"
