module GRAM

export BODY_NO, BODY_VENUS, BODY_EARTH, BODY_MARS, BODY_JUPITER, BODY_SATURN, BODY_URANUS, BODY_NEPTUNE, BODY_TITAN
export GAS_ARGON, GAS_HELIUM, GAS_HYDROGEN, GAS_DIHYDROGEN, GAS_NITROGEN, GAS_DINITROGEN, GAS_OXYGEN, GAS_DIOXYGEN
export GAS_METHANE, GAS_CARBON_MONOXIDE, GAS_CARBON_DIOXIDE, GAS_OZONE, GAS_NITROUS_OXIDE, GAS_WATER
export Atmosphere, PositionC, DynamicsStateC, DensityStateC, WindsStateC, GasesStateC, ConstituentGasC, PerturbationStateC, EphemerisStateC, TrajectoryPointC
export MarsStateC, DailyDynamicsStateC, EarthStateC, EarthPertsC, EarthSurfaceC, EarthBoundaryLayerC
export set_library!, initialize!, create_atmosphere, copy_atmosphere, set_start_time!, set_delta!, set_position!, update!, get_start_time, get_position, get_dynamics_state, get_density_state, get_winds_state, get_gases_state, get_constituent_gas, get_ephemeris_state, get_perturbation_state
export enable_console_output!, try_get_spice_path, try_get_data_paths, set_spice_lsk!, set_spice_pck!, set_spice_kernel!, load_spice_file!
export set_seed!, set_min_relative_step_size!, set_perturbation_scales!, set_perturbation_action!, add_auxiliary_atmosphere!, set_auxiliary_values!, set_ephemeris_state!, set_ephemeris_fast_mode!, set_subsolar_update_time!
export generate_trajectory, generate_monte_carlo_trajectories
export set_map_year!, set_mgcm_dust_levels!, set_dust_storm!, set_dust_density!, set_f107!, set_wind_scales!, set_mola_heights!, set_min_max!
export set_planetary_radii!, set_height_offset_model!, set_height_above_surface!, set_perturbation_wavelength_scale!, set_exospheric_temperature!, set_wave_defaults!, set_wave_file!
export set_areoid_radius_callback!, set_topographic_height_callback!, set_callback_data!
export get_mars_state, get_daily_dynamics_state, get_mars_gases_state, get_version_string
export mars_try_get_spice_path, mars_try_get_data_paths, mars_set_spice_lsk!, mars_set_spice_pck!, mars_set_spice_kernel!, mars_initialize!, mars_load_spice_file!, create_mars_atmosphere, copy_mars_atmosphere, mars_close!, mars_update!, mars_get_error_message
export mars_set_start_time!, mars_set_position!, mars_set_delta!, mars_set_seed!, mars_set_min_relative_step_size!, mars_set_perturbation_scales!, mars_add_auxiliary_atmosphere!, mars_set_auxiliary_values!, mars_set_perturbation_action!, mars_set_ephemeris_state!, mars_set_ephemeris_fast_mode!, mars_set_subsolar_update_time!
export mars_get_start_time, mars_get_position, mars_get_dynamics_state, mars_get_density_state, mars_get_winds_state, mars_get_ephemeris_state, mars_get_perturbation_state
export mars_set_map_year!, mars_set_planetary_radii!, mars_set_height_offset_model!, mars_set_height_above_surface!, mars_set_mgcm_dust_levels!, mars_set_dust_storm!, mars_set_dust_density!, mars_set_f107!, mars_set_perturbation_wavelength_scale!, mars_set_wind_scales!, mars_set_mola_heights!, mars_set_min_max!, mars_set_exospheric_temperature!, mars_set_wave_defaults!, mars_set_wave_file!, mars_set_areoid_radius_callback!, mars_set_topographic_height_callback!, mars_set_callback_data!
export mars_get_version_string, mars_get_daily_dynamics_state, mars_get_mars_state, mars_get_mars_gases_state
export earth_try_get_spice_path, earth_try_get_data_paths, earth_set_spice_lsk!, earth_set_spice_pck!, earth_set_spice_kernel!, earth_initialize!, earth_load_spice_file!, create_earth_atmosphere, copy_earth_atmosphere, earth_close!, earth_update!, earth_get_error_message, earth_get_version_string, earth_set_thermosphere_model!, earth_set_surface_roughness!, earth_set_atmos_path!, earth_set_merra2_path!, earth_set_ncep_path!, earth_set_merra2_parameters!, earth_set_use_ncep!, earth_set_ncep_parameters!, earth_set_rra_path!, earth_set_rra_site_list!, earth_set_rra_parameters!, earth_set_use_rra!, earth_set_solar_parameters!, earth_set_jb2008_parameters!, earth_set_initial_perturbations!, earth_set_patchiness!, earth_set_start_time!, earth_set_position!, earth_set_delta!, earth_set_seed!, earth_set_perturbation_scales!, earth_add_auxiliary_atmosphere!, earth_set_auxiliary_values!, earth_set_perturbation_action!, earth_set_ephemeris_state!, earth_set_ephemeris_fast_mode!, earth_set_subsolar_update_time!, earth_get_start_time, earth_get_position, earth_get_dynamics_state, earth_get_density_state, earth_get_winds_state, earth_get_ephemeris_state, earth_get_perturbation_state, earth_get_gases_state, earth_get_state, earth_get_perts, earth_get_surface, earth_get_boundary_layer
export venus_try_get_spice_path, venus_set_spice_lsk!, venus_set_spice_pck!, venus_set_spice_kernel!, venus_initialize!, venus_load_spice_file!, create_venus_atmosphere, copy_venus_atmosphere, venus_close!, venus_set_start_time!, venus_set_position!, venus_set_delta!, venus_set_seed!, venus_set_min_relative_step_size!, venus_set_perturbation_scales!, venus_add_auxiliary_atmosphere!, venus_set_auxiliary_values!, venus_set_perturbation_action!, venus_set_ephemeris_state!, venus_set_ephemeris_fast_mode!, venus_set_subsolar_update_time!, venus_update!, venus_get_error_message, venus_get_start_time, venus_get_version_string, venus_get_position, venus_get_dynamics_state, venus_get_density_state, venus_get_winds_state, venus_get_gases_state, venus_get_ephemeris_state, venus_get_perturbation_state
export jupiter_try_get_spice_path, jupiter_set_spice_lsk!, jupiter_set_spice_pck!, jupiter_set_spice_kernel!, jupiter_initialize!, jupiter_load_spice_file!, create_jupiter_atmosphere, copy_jupiter_atmosphere, jupiter_close!, jupiter_set_start_time!, jupiter_set_position!, jupiter_set_delta!, jupiter_set_seed!, jupiter_set_min_relative_step_size!, jupiter_set_perturbation_scales!, jupiter_add_auxiliary_atmosphere!, jupiter_set_auxiliary_values!, jupiter_set_perturbation_action!, jupiter_set_ephemeris_state!, jupiter_set_ephemeris_fast_mode!, jupiter_set_subsolar_update_time!, jupiter_update!, jupiter_get_error_message, jupiter_get_start_time, jupiter_get_version_string, jupiter_get_position, jupiter_get_dynamics_state, jupiter_get_density_state, jupiter_get_winds_state, jupiter_get_gases_state, jupiter_get_ephemeris_state, jupiter_get_perturbation_state
export uranus_try_get_spice_path, uranus_set_spice_lsk!, uranus_set_spice_pck!, uranus_set_spice_kernel!, uranus_initialize!, uranus_load_spice_file!, create_uranus_atmosphere, copy_uranus_atmosphere, uranus_close!, uranus_set_start_time!, uranus_set_position!, uranus_set_delta!, uranus_set_seed!, uranus_set_min_relative_step_size!, uranus_set_perturbation_scales!, uranus_add_auxiliary_atmosphere!, uranus_set_auxiliary_values!, uranus_set_perturbation_action!, uranus_set_ephemeris_state!, uranus_set_ephemeris_fast_mode!, uranus_set_subsolar_update_time!, uranus_update!, uranus_get_error_message, uranus_get_start_time, uranus_get_version_string, uranus_get_position, uranus_get_dynamics_state, uranus_get_density_state, uranus_get_winds_state, uranus_get_gases_state, uranus_get_ephemeris_state, uranus_get_perturbation_state
export neptune_try_get_spice_path, neptune_set_spice_lsk!, neptune_set_spice_pck!, neptune_set_spice_kernel!, neptune_initialize!, neptune_load_spice_file!, create_neptune_atmosphere, copy_neptune_atmosphere, neptune_close!, neptune_set_start_time!, neptune_set_position!, neptune_set_delta!, neptune_set_seed!, neptune_set_min_relative_step_size!, neptune_set_perturbation_scales!, neptune_add_auxiliary_atmosphere!, neptune_set_auxiliary_values!, neptune_set_perturbation_action!, neptune_set_ephemeris_state!, neptune_set_ephemeris_fast_mode!, neptune_set_subsolar_update_time!, neptune_update!, neptune_get_error_message, neptune_get_start_time, neptune_get_version_string, neptune_get_position, neptune_get_dynamics_state, neptune_get_density_state, neptune_get_winds_state, neptune_get_gases_state, neptune_get_ephemeris_state, neptune_get_perturbation_state, neptune_set_dinitrogen_mole_fraction!, neptune_set_min_max_factor!, neptune_get_min_max_factor
export titan_try_get_spice_path, titan_set_spice_lsk!, titan_set_spice_pck!, titan_set_spice_kernel!, titan_initialize!, titan_load_spice_file!, create_titan_atmosphere, copy_titan_atmosphere, titan_close!, titan_set_start_time!, titan_set_position!, titan_set_delta!, titan_set_seed!, titan_set_min_relative_step_size!, titan_set_perturbation_scales!, titan_add_auxiliary_atmosphere!, titan_set_auxiliary_values!, titan_set_perturbation_action!, titan_set_ephemeris_state!, titan_set_ephemeris_fast_mode!, titan_set_subsolar_update_time!, titan_update!, titan_get_error_message, titan_get_start_time, titan_get_version_string, titan_get_position, titan_get_dynamics_state, titan_get_density_state, titan_get_winds_state, titan_get_gases_state, titan_get_ephemeris_state, titan_get_perturbation_state, titan_set_min_max_factor!, titan_get_min_max_factor, titan_set_methane_mole_fraction!, titan_set_model_type!
export get_error_message, close!

include("types.jl")
include("generic.jl")
include("mars.jl")
include("earth.jl")
include("outer_planets.jl")
include("aliases.jl")

end # module GRAM
