# Includes are ordered by type and function dependencies.
include(joinpath(@__DIR__, "types.jl"))
include(joinpath(@__DIR__, "constraints.jl"))
include(joinpath(@__DIR__, "condensed_core.jl"))
include(joinpath(@__DIR__, "objectives.jl"))
include(joinpath(@__DIR__, "density_adapter.jl"))
include(joinpath(@__DIR__, "scenario_config.jl"))
include(joinpath(@__DIR__, "trajectory_reference.jl"))
include(joinpath(@__DIR__, "prediction_model.jl"))
include(joinpath(@__DIR__, "qp_solver.jl"))
include(joinpath(@__DIR__, "area_mapping.jl"))
include(joinpath(@__DIR__, "plan_validation.jl"))
include(joinpath(@__DIR__, "spaceagora_control_model.jl"))
include(joinpath(@__DIR__, "campaign_control_model.jl"))
